version: '2'

services:
  _base:
    build:
      context: .
      dockerfile: Dockerfile-dev-support
    volumes:
      - .:/go/src/yc-zhang/sample-price-service
    working_dir: /go/src/yc-zhang/sample-price-service
    environment:
      REDIS_SERVER: redis:6379

  dev:
    extends:
      service: _base
    ports:
      - 9090:8080
    command: "go run main.go"
    depends_on:
      - redis

  redis:
    image: redis:3.0
