version: '2'

services:
  _base:
    build:
      context: .
      dockerfile: Dockerfile-dev-support
    volumes:
      - .:/go/src/yc-zhang/sample-price-service
    working_dir: /go/src/yc-zhang/sample-price-service

  dev:
    extends:
      service: _base
